line-length = 120 # The formatter wraps lines at a length of x

[pycodestyle]
max-line-length = 240 # E501 reports lines that exceed the length of 100.

# [tool.ruff]
# include = ["/home/bartosz/.local/lib/python3.11/site-packages/**/*.py"]
